export const movies = [
  {
    __typename: 'Movie',
    adult: null,
    backdrop_path: null,
    genre_ids: null,
    genres: null,
    id: '436270',
    original_language: null,
    original_title: null,
    overview: null,
    popularity: null,
    posterPath: 'https://image.tmdb.org/t/p/w300/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg',
    releaseDate: '2022-10-19',
    title: 'Black Adam',
    video: null,
    vote_average: null,
    vote_count: null,
  },
  {
    __typename: 'Movie',
    adult: null,
    backdrop_path: null,
    genre_ids: null,
    genres: null,
    id: '1013860',
    original_language: null,
    original_title: null,
    overview: null,
    popularity: null,
    posterPath: 'https://image.tmdb.org/t/p/w300/g4yJTzMtOBUTAR2Qnmj8TYIcFVq.jpg',
    releaseDate: '2022-11-15',
    title: 'R.I.P.D. 2: Rise of the Damned',
    video: null,
    vote_average: null,
    vote_count: null,
  },
  {
    __typename: 'Movie',
    adult: null,
    backdrop_path: null,
    genre_ids: null,
    genres: null,
    id: '338958',
    original_language: null,
    original_title: null,
    overview: null,
    popularity: null,
    posterPath: 'https://image.tmdb.org/t/p/w300/4x3pt6hoLblBeHebUa4OyiVXFiM.jpg',
    releaseDate: '2022-11-16',
    title: 'Disenchanted',
    video: null,
    vote_average: null,
    vote_count: null,
  },
  {
    __typename: 'Movie',
    adult: null,
    backdrop_path: null,
    genre_ids: null,
    genres: null,
    id: '505642',
    original_language: null,
    original_title: null,
    overview: null,
    popularity: null,
    posterPath: 'https://image.tmdb.org/t/p/w300/sv1xJUazXeYqALzczSZ3O6nkH75.jpg',
    releaseDate: '2022-11-09',
    title: 'Black Panther: Wakanda Forever',
    video: null,
    vote_average: null,
    vote_count: null,
  },
  {
    __typename: 'Movie',
    adult: null,
    backdrop_path: null,
    genre_ids: null,
    genres: null,
    id: '882598',
    original_language: null,
    original_title: null,
    overview: null,
    popularity: null,
    posterPath: 'https://image.tmdb.org/t/p/w300/aPqcQwu4VGEewPhagWNncDbJ9Xp.jpg',
    releaseDate: '2022-09-23',
    title: 'Smile',
    video: null,
    vote_average: null,
    vote_count: null,
  },
  {
    __typename: 'Movie',
    adult: null,
    backdrop_path: null,
    genre_ids: null,
    genres: null,
    id: '966220',
    original_language: null,
    original_title: null,
    overview: null,
    popularity: null,
    posterPath: 'https://image.tmdb.org/t/p/w300/lZOODJzwuQo0etJJyBBZJOSdZcW.jpg',
    releaseDate: '2022-05-03',
    title: 'Sniper: The White Raven',
    video: null,
    vote_average: null,
    vote_count: null,
  },
  {
    __typename: 'Movie',
    adult: null,
    backdrop_path: null,
    genre_ids: null,
    genres: null,
    id: '829799',
    original_language: null,
    original_title: null,
    overview: null,
    popularity: null,
    posterPath: 'https://image.tmdb.org/t/p/w300/xdmmd437QdjcCls8yCQxrH5YYM4.jpg',
    releaseDate: '2022-11-11',
    title: 'Paradise City',
    video: null,
    vote_average: null,
    vote_count: null,
  },
  {
    __typename: 'Movie',
    adult: null,
    backdrop_path: null,
    genre_ids: null,
    genres: null,
    id: '988233',
    original_language: null,
    original_title: null,
    overview: null,
    popularity: null,
    posterPath: 'https://image.tmdb.org/t/p/w300/xFJHb43ZAnnuiDztxZYsmyopweb.jpg',
    releaseDate: '2022-11-01',
    title: 'Hex',
    video: null,
    vote_average: null,
    vote_count: null,
  },
  {
    __typename: 'Movie',
    adult: null,
    backdrop_path: null,
    genre_ids: null,
    genres: null,
    id: '551271',
    original_language: null,
    original_title: null,
    overview: null,
    popularity: null,
    posterPath: 'https://image.tmdb.org/t/p/w300/4njdAkiBdC5LnFApeXSkFQ78GdT.jpg',
    releaseDate: '2022-09-08',
    title: 'Medieval',
    video: null,
    vote_average: null,
    vote_count: null,
  },
  {
    __typename: 'Movie',
    adult: null,
    backdrop_path: null,
    genre_ids: null,
    genres: null,
    id: '862965',
    original_language: null,
    original_title: null,
    overview: null,
    popularity: null,
    posterPath: 'https://image.tmdb.org/t/p/w300/iZvzMpREGiqDQ5eYbx8z70qPgst.jpg',
    releaseDate: '2022-08-12',
    title: 'Emily the Criminal',
    video: null,
    vote_average: null,
    vote_count: null,
  },
  {
    __typename: 'Movie',
    adult: null,
    backdrop_path: null,
    genre_ids: null,
    genres: null,
    id: '948276',
    original_language: null,
    original_title: null,
    overview: null,
    popularity: null,
    posterPath: 'https://image.tmdb.org/t/p/w300/uAeZI1JJbLPq7Bu5dziH7emHeu7.jpg',
    releaseDate: '2022-11-10',
    title: 'Lost Bullet 2',
    video: null,
    vote_average: null,
    vote_count: null,
  },
  {
    __typename: 'Movie',
    adult: null,
    backdrop_path: null,
    genre_ids: null,
    genres: null,
    id: '829280',
    original_language: null,
    original_title: null,
    overview: null,
    popularity: null,
    posterPath: 'https://image.tmdb.org/t/p/w300/tegBpjM5ODoYoM1NjaiHVLEA0QM.jpg',
    releaseDate: '2022-11-04',
    title: 'Enola Holmes 2',
    video: null,
    vote_average: null,
    vote_count: null,
  },
  {
    __typename: 'Movie',
    adult: null,
    backdrop_path: null,
    genre_ids: null,
    genres: null,
    id: '676701',
    original_language: null,
    original_title: null,
    overview: null,
    popularity: null,
    posterPath: 'https://image.tmdb.org/t/p/w300/jvIVl8zdNSOAJImw1elQEzxStMN.jpg',
    releaseDate: '2022-08-24',
    title: 'Tad the Lost Explorer and the Emerald Tablet',
    video: null,
    vote_average: null,
    vote_count: null,
  },
  {
    __typename: 'Movie',
    adult: null,
    backdrop_path: null,
    genre_ids: null,
    genres: null,
    id: '663712',
    original_language: null,
    original_title: null,
    overview: null,
    popularity: null,
    posterPath: 'https://image.tmdb.org/t/p/w300/b6IRp6Pl2Fsq37r9jFhGoLtaqHm.jpg',
    releaseDate: '2022-10-06',
    title: 'Terrifier 2',
    video: null,
    vote_average: null,
    vote_count: null,
  },
  {
    __typename: 'Movie',
    adult: null,
    backdrop_path: null,
    genre_ids: null,
    genres: null,
    id: '979924',
    original_language: null,
    original_title: null,
    overview: null,
    popularity: null,
    posterPath: 'https://image.tmdb.org/t/p/w300/a14BbSHvLgzCdbDD6tAL8OBVKL1.jpg',
    releaseDate: '2022-10-31',
    title: 'On the Line',
    video: null,
    vote_average: null,
    vote_count: null,
  },
  {
    __typename: 'Movie',
    adult: null,
    backdrop_path: null,
    genre_ids: null,
    genres: null,
    id: '899294',
    original_language: null,
    original_title: null,
    overview: null,
    popularity: null,
    posterPath: 'https://image.tmdb.org/t/p/w300/5NpXoAi3nEQkEgLO09nmotPfyNa.jpg',
    releaseDate: '2022-06-03',
    title: 'Frank and Penelope',
    video: null,
    vote_average: null,
    vote_count: null,
  },
  {
    __typename: 'Movie',
    adult: null,
    backdrop_path: null,
    genre_ids: null,
    genres: null,
    id: '846778',
    original_language: null,
    original_title: null,
    overview: null,
    popularity: null,
    posterPath: 'https://image.tmdb.org/t/p/w300/uNzgeMetu9l4q9NDw7gtiUFwPOJ.jpg',
    releaseDate: '2022-09-09',
    title: 'Margaux',
    video: null,
    vote_average: null,
    vote_count: null,
  },
  {
    __typename: 'Movie',
    adult: null,
    backdrop_path: null,
    genre_ids: null,
    genres: null,
    id: '985939',
    original_language: null,
    original_title: null,
    overview: null,
    popularity: null,
    posterPath: 'https://image.tmdb.org/t/p/w300/spCAxD99U1A6jsiePFoqdEcY0dG.jpg',
    releaseDate: '2022-08-11',
    title: 'Fall',
    video: null,
    vote_average: null,
    vote_count: null,
  },
  {
    __typename: 'Movie',
    adult: null,
    backdrop_path: null,
    genre_ids: null,
    genres: null,
    id: '872177',
    original_language: null,
    original_title: null,
    overview: null,
    popularity: null,
    posterPath: 'https://image.tmdb.org/t/p/w300/9qG7cBhu444BYmcIOeoLJoCBMuO.jpg',
    releaseDate: '2022-04-29',
    title: 'Corrective Measures',
    video: null,
    vote_average: null,
    vote_count: null,
  },
  {
    __typename: 'Movie',
    adult: null,
    backdrop_path: null,
    genre_ids: null,
    genres: null,
    id: '760204',
    original_language: null,
    original_title: null,
    overview: null,
    popularity: null,
    posterPath: 'https://image.tmdb.org/t/p/w300/ifRFLx83Xk1DcwAS3OScgI6HmWO.jpg',
    releaseDate: '2022-10-28',
    title: 'The Lair',
    video: null,
    vote_average: null,
    vote_count: null,
  },
]
